### ISSUE TITLE
Crash on game initialisation when ArsMagica is enabled

### ISSUE THREAD

**Issue by Edern76** [EdwinMindcraft/ArsMagica2#31]
- OS : Windows 10 x64
- Minecraft Version : 1.10.2 with Forge 12.18.3.2185
- Mod Version : 1.5.0C-4
- Description : The game crashes past the Forge loading screen when ArsMagica is enabled
- Error log : `

20:17:23 | game |   | error | 2018-02-07 19:17:23,774 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream   <log4j:Event logger="LaunchWrapper" timestamp="1518027443794" level="INFO" thread="main">     <log4j:Message><![CDATA[Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker]]></log4j:Message>   </log4j:Event>
-- | -- | -- | -- | --
20:17:23 | monitor | Process Monitor | error | expected <
20:17:24 | game |   | error | 2018-02-07 19:17:24,085 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream 2018-02-07 19:17:24,091 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream   <log4j:Event logger="FML" timestamp="1518027444094" level="WARN" thread="main">     <log4j:Message><![CDATA[The coremod codechicken.lib.asm.CCLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft]]></log4j:Message>   </log4j:Event>
20:17:24 | monitor | Process Monitor | error | expected <
19:17:48 | brandonscore | Client thread | error | Could not create config directory! Things are probably going to break!
19:17:57 | draconicevolution | Client thread | error | Did not find any mod docs in the selected docs folder.
19:18:38 | FML | Client thread | error | Unable to load block sub-model: 'arsmagica2:block/celestial_prism_cullface.json net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Loader am2.client.models.CullfaceModelLoader@2e055d52 returned missing model while loading model arsmagica2:block/celestial_prism_cullface.json 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:157) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModelOrLogError(ModelLoaderRegistry.java:203) 	at net.minecraftforge.client.model.BlockStateLoader$ForgeVariant.process(BlockStateLoader.java:206) 	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.<init>(ModelLoader.java:756) 	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1185) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:325) 	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:185) 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) 	at net.minecraft.client.main.Main.main(SourceFile:124) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
19:19:07 | FML | Client thread | error | Exception loading model for variant arsmagica2:ice_effigy#inventory, normal location exception:  net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model arsmagica2:item/ice_effigy with loader VanillaLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:317) 	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:185) 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) 	at net.minecraft.client.main.Main.main(SourceFile:124) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.io.FileNotFoundException: arsmagica2:models/item/ice_effigy.json 	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) 	at net.minecraft.client.renderer.block.model.ModelBakery.func_177594_c(ModelBakery.java:333) 	at net.minecraftforge.client.model.ModelLoader.access$1100(ModelLoader.java:118) 	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:868) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 14 more
19:19:07 | FML | Client thread | error | Exception loading model for variant arsmagica2:ice_effigy#inventory, blockstate location exception:  net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model arsmagica2:ice_effigy#inventory with loader VariantLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:325) 	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:185) 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) 	at net.minecraft.client.main.Main.main(SourceFile:124) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException 	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:78) 	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1184) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 14 more
19:19:07 | FML | Client thread | error | Exception loading model for variant arsmagica2:tome#inventory, normal location exception:  net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model arsmagica2:item/tome with loader VanillaLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:317) 	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:185) 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) 	at net.minecraft.client.main.Main.main(SourceFile:124) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.io.FileNotFoundException: arsmagica2:models/item/tome.json 	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) 	at net.minecraft.client.renderer.block.model.ModelBakery.func_177594_c(ModelBakery.java:333) 	at net.minecraftforge.client.model.ModelLoader.access$1100(ModelLoader.java:118) 	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:868) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 14 more
19:19:07 | FML | Client thread | error | Exception loading model for variant arsmagica2:tome#inventory, blockstate location exception:  net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model arsmagica2:tome#inventory with loader VariantLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:325) 	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:185) 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) 	at net.minecraft.client.main.Main.main(SourceFile:124) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException 	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:78) 	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1184) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 14 more
19:19:07 | FML | Client thread | error | Exception loading model for variant props:blockFake#facing=north net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model props:blockFake#facing=north with loader VariantLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:241) 	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:154) 	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:229) 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:146) 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) 	at net.minecraft.client.main.Main.main(SourceFile:124) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException 	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:78) 	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1184) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 15 more
19:19:07 | FML | Client thread | error | Exception loading model for variant arsmagica2:lightning_effigy#normal net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model arsmagica2:lightning_effigy#normal with loader VariantLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:241) 	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:154) 	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:229) 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:146) 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) 	at net.minecraft.client.main.Main.main(SourceFile:124) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model arsmagica2:block/lightning_effigy with loader VanillaLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.<init>(ModelLoader.java:752) 	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1185) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 15 more Caused by: java.io.FileNotFoundException: arsmagica2:models/block/lightning_effigy.json 	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) 	at net.minecraft.client.renderer.block.model.ModelBakery.func_177594_c(ModelBakery.java:333) 	at net.minecraftforge.client.model.ModelLoader.access$1100(ModelLoader.java:118) 	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:868) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 18 more
19:19:07 | FML | Client thread | error | Exception loading model for variant props:blockProps#facing=east net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model props:blockProps#facing=east with loader VariantLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:241) 	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:154) 	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:229) 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:146) 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) 	at net.minecraft.client.main.Main.main(SourceFile:124) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException 	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:78) 	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1184) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 15 more
19:19:07 | FML | Client thread | error | Exception loading model for variant arsmagica2:core#inventory, normal location exception:  net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model arsmagica2:item/core with loader VanillaLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:317) 	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:185) 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) 	at net.minecraft.client.main.Main.main(SourceFile:124) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.io.FileNotFoundException: arsmagica2:models/item/core.json 	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) 	at net.minecraft.client.renderer.block.model.ModelBakery.func_177594_c(ModelBakery.java:333) 	at net.minecraftforge.client.model.ModelLoader.access$1100(ModelLoader.java:118) 	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:868) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 14 more
19:19:07 | FML | Client thread | error | Exception loading model for variant arsmagica2:core#inventory, blockstate location exception:  net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model arsmagica2:core#inventory with loader VariantLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:325) 	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:185) 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:147) 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) 	at net.minecraft.client.main.Main.main(SourceFile:124) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException 	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:78) 	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1184) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 14 more
19:19:07 | FML | Client thread | error | Exception loading model for variant props:blockFake#facing=east net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model props:blockFake#facing=east with loader VariantLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:241) 	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:154) 	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:229) 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:146) 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) 	at net.minecraft.client.main.Main.main(SourceFile:124) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException 	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:78) 	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1184) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 15 more
19:19:07 | FML | Client thread | error | Exception loading model for variant props:blockProps#facing=north net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model props:blockProps#facing=north with loader VariantLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:241) 	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:154) 	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:229) 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:146) 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) 	at net.minecraft.client.main.Main.main(SourceFile:124) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException 	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:78) 	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1184) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 15 more
19:19:07 | FML | Client thread | error | Suppressed additional 14 model loading errors for domain arsmagica2
19:19:07 | FML | Client thread | error | Suppressed additional 3 model loading errors for domain props
19:20:50 | net.minecraft.client.renderer.texture.TextureMap | Client thread | error | Using missing texture, unable to load arsmagica2:textures/items/essence_none.png, java.io.FileNotFoundException
19:20:50 | net.minecraft.client.renderer.texture.TextureMap | Client thread | error | Using missing texture, unable to load arsmagica2:textures/items/spells/shapes/Toggle.png, java.io.FileNotFoundException
19:21:00 | net.minecraft.client.renderer.texture.TextureMap | Client thread | error | Using missing texture, unable to load thaumcraft:textures//blocks/centrifuge.png, java.io.FileNotFoundException
19:21:01 | net.minecraft.client.renderer.texture.TextureMap | Client thread | error | Using missing texture, unable to load arsmagica2:textures/items/FlickerOperatorBlank.png, java.io.FileNotFoundException
19:21:03 | net.minecraft.client.renderer.texture.TextureMap | Client thread | error | Using missing texture, unable to load arsmagica2:textures/items/potion_bundle.png, java.io.FileNotFoundException

`

**Comment by Edern76** [comment]
Nevermind, thought the error was related to ArsMagica when I saw a bunch of missing textures in the console log, but in fact it was Java running out of allocated memory which caused the problem.
