### ISSUE TITLE
[1.10.2- ArsMagica2-1.5.0C-9 & 10] Inscription table not working when running in server

### ISSUE THREAD

**Issue by tanisdlj** [EdwinMindcraft/ArsMagica2#42]
#36 
In single player works. The issue only happens when you are playing on a Server.
Once you drop the book and quill in the inscription table, is gone, and the server throws the following exception:

    [20:39:36] [Server thread/FATAL]: Error executing task
    java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
    Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at am2.common.container.slot.SlotInscriptionTable.func_75215_d(SlotInscriptionTable.java:58) ~[SlotInscriptionTable.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:302) ~[abd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1112) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:33) ~[ir.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:10) ~[ir.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
    Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
	at am2.common.container.slot.SlotInscriptionTable.func_75215_d(SlotInscriptionTable.java:58) ~[SlotInscriptionTable.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:302) ~[abd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1112) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:33) ~[ir.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:10) ~[ir.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
    Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
	at am2.common.container.slot.SlotInscriptionTable.func_75215_d(SlotInscriptionTable.java:58) ~[SlotInscriptionTable.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:302) ~[abd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1112) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:33) ~[ir.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:10) ~[ir.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
    [20:39:38] [Server thread/FATAL]: Error executing task
    java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
    Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at am2.common.container.slot.SlotInscriptionTable.func_75215_d(SlotInscriptionTable.java:58) ~[SlotInscriptionTable.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:302) ~[abd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1112) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:33) ~[ir.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:10) ~[ir.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
    [20:39:38] [Server thread/FATAL]: Error executing task
    java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
    Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at am2.common.container.slot.SlotInscriptionTable.func_75215_d(SlotInscriptionTable.java:58) ~[SlotInscriptionTable.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:302) ~[abd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1112) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:33) ~[ir.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:10) ~[ir.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
`

**Comment by tanisdlj** [comment]
Happening in 1.5.0C-10 too:

> [21:14:24] [Server thread/FATAL]: Error executing task
> java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
>         at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
>         at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
> Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
>         at am2.common.container.slot.SlotInscriptionTable.func_75215_d(SlotInscriptionTable.java:58) ~[SlotInscriptionTable.class:?]
>         at net.minecraft.inventory.Container.func_184996_a(Container.java:302) ~[abd.class:?]
>         at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1112) ~[me.class:?]
>         at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:33) ~[ir.class:?]
>         at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:10) ~[ir.class:?]
>         at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
>         at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
>         ... 5 more
> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
>         at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
>         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
>         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
>         at am2.common.container.slot.SlotInscriptionTable.func_75215_d(SlotInscriptionTable.java:58) ~[SlotInscriptionTable.class:?]
>         at net.minecraft.inventory.Container.func_184996_a(Container.java:302) ~[abd.class:?]
>         at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1112) ~[me.class:?]
>         at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:33) ~[ir.class:?]
>         at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:10) ~[ir.class:?]
>         at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
>         at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
>         ... 5 more
> Caused by: java.lang.NullPointerException
>         at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
>         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
>         at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
>         at am2.common.container.slot.SlotInscriptionTable.func_75215_d(SlotInscriptionTable.java:58) ~[SlotInscriptionTable.class:?]
>         at net.minecraft.inventory.Container.func_184996_a(Container.java:302) ~[abd.class:?]
>         at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1112) ~[me.class:?]
>         at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:33) ~[ir.class:?]
>         at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:10) ~[ir.class:?]
>         at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
>         at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
>         ... 5 more
